swagger: '2.0'

info:
  version: "0.0.1"
  title: OSU Dining Balances API
produces:
  - application/json
paths:
  /diningbalances/{osuID}:
    get:
      tags:
        - balances
      description: "Get a single event by ID"
      produces:
        - application/json
      parameters:
        - name: osuID
          in: path
          description: "ID requested user"
          required: true
          type: integer
      responses:
        200:
          description: "Successful response"
          schema:
            $ref: "#/definitions/ResultObject"
        404:
          description: "Not found"
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/Error"

definitions:
  ResultObject:
    properties:
      data:
        $ref: "#/definitions/ResourceObject"
  ResultObjects:
    properties:
      data:
        type: array
        items:
          $ref: "#/definitions/ResourceObject"
  ResourceObject:
    properties:
      id:
        type: number
        format: integer
      type:
        type: string
      attributes:
        $ref: "#/definitions/Attributes"

  Attributes:
    properties:
      name:
        type: string
      type:
        type: string
      orange_rewards_balance:
        type: number
        format: float
      meal_plan_balance:
        type: number
        format: float

  Error:
    type: object
    properties:
      status:
        type: integer
        format: int32
      developerMessage:
        type: string
      userMesage:
        type: string
      code:
        type: integer
      details:
        type: string
